-- Run with a Snowflake role allowed to create application objects.
CREATE DATABASE IF NOT EXISTS DEBIT_NOTE_APP;
CREATE SCHEMA IF NOT EXISTS DEBIT_NOTE_APP.CORE;

CREATE STAGE IF NOT EXISTS DEBIT_NOTE_APP.CORE.PDF_STAGE
  DIRECTORY = (ENABLE = TRUE)
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

CREATE STAGE IF NOT EXISTS DEBIT_NOTE_APP.CORE.REPORT_STAGE
  DIRECTORY = (ENABLE = TRUE)
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

CREATE TABLE IF NOT EXISTS DEBIT_NOTE_APP.CORE.PROCESSING_RUNS (
  RUN_ID VARCHAR PRIMARY KEY,
  STARTED_AT TIMESTAMP_TZ,
  COMPLETED_AT TIMESTAMP_TZ,
  STATUS VARCHAR,
  USER_NAME VARCHAR,
  PDF_COUNT NUMBER,
  RECORD_COUNT NUMBER,
  EXCEPTION_COUNT NUMBER,
  TOTAL_AMOUNT NUMBER(18,2)
);

CREATE TABLE IF NOT EXISTS DEBIT_NOTE_APP.CORE.PROCESSED_REGISTRY (
  FILE_HASH VARCHAR PRIMARY KEY,
  PDF_NAME VARCHAR,
  VENDOR_NAME VARCHAR,
  INVOICE_REF_NO VARCHAR,
  RUN_ID VARCHAR,
  STAGE_PATH VARCHAR,
  PROCESSED_AT TIMESTAMP_TZ,
  USER_NAME VARCHAR
);

CREATE TABLE IF NOT EXISTS DEBIT_NOTE_APP.CORE.EXTRACTED_RECORDS (
  RUN_ID VARCHAR,
  RECORD_JSON VARCHAR
);

CREATE TABLE IF NOT EXISTS DEBIT_NOTE_APP.CORE.PROCESSING_EXCEPTIONS (
  RUN_ID VARCHAR,
  ISSUE_JSON VARCHAR
);

CREATE TABLE IF NOT EXISTS DEBIT_NOTE_APP.CORE.CUSTOMER_MASTER (
  VENDOR_NAME VARCHAR,
  VENDOR_GST_CODE VARCHAR,
  CUSTOMER_STATE VARCHAR,
  PLANT VARCHAR,
  PLANT_GST VARCHAR,
  DEFAULT_CLAIM_TYPE VARCHAR,
  ACTIVE BOOLEAN DEFAULT TRUE,
  UPDATED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_BY VARCHAR DEFAULT CURRENT_USER()
);

-- Replace names below with your actual team roles.
-- GRANT USAGE ON DATABASE DEBIT_NOTE_APP TO ROLE <APP_ROLE>;
-- GRANT USAGE ON SCHEMA DEBIT_NOTE_APP.CORE TO ROLE <APP_ROLE>;
-- GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA DEBIT_NOTE_APP.CORE TO ROLE <APP_ROLE>;
-- GRANT READ, WRITE ON STAGE DEBIT_NOTE_APP.CORE.PDF_STAGE TO ROLE <APP_ROLE>;
-- GRANT READ, WRITE ON STAGE DEBIT_NOTE_APP.CORE.REPORT_STAGE TO ROLE <APP_ROLE>;
